config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :image, styles: { medium: '500x500>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def index
    if signed_in?
      @posts = Post.all.order('created_at DESC')
    else
      redirect_to new_user_session_path
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = 'Success!'
      redirect_to post_path(@post)
    else
      flash[:error] = @post.errors.full_messages
      render 'new'
    end
  end

  def destroy
    @post = Post.destroy(params[:id])
    redirect_to post_path
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params[:id])
      flash[:success] = 'Pic was updated!'
      redirect_to @post
    else
      render 'edit'
    end
  end

  private

  def post_params
    params.require(:post).permit(:image, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramApp</title>
    <%= csrf_meta_tags %>

    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <style>
      body {
        padding-top: 54px;
      }
      @media (min-width: 992px) {
        body {
          padding-top: 56px;
        }
      }

    </style>
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to "Instagram", root_url, class: "navbar-brand" %>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
               <a class="nav-link" href="/posts/new">New Post
                 <span class="sr-only">(current)</span>
               </a>
             </li>
             <li class="nav-item">
               <a class="nav-link" href="/users/sign_up">Sign Up
                 <span class="sr-only">(current)</span>
               </a>
             </li>
            <% if current_user %>
              <li class="nav-item">
                <a class="nav-link">
                  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                  <span class="sr-only">(current)</span>
                </a>
              </li>
            <% else %>
              <li class="nav-item">
                <a class="nav-link">
                <%= link_to "Login", new_user_session_path %>
                <span class="sr-only">(current)</span>
              </a>
              </li>
            <% end %>
            </li>

          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <%flash.each do |a, b| %>
          <div class="alert alert-success"> <%= b %> </div>
          <%end%>
          <br>
          <br>
          <%= yield %>
        </div>
      </div>
    </div>

    <div class="container">


  </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>

<div class="field">
    <%= f.label :image %>
    <%= f.file_field :image%>
</div>

  <br>

<div class="field">
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>

  <br>
  
<div class="actions">
  <%= f.submit %>
</div>

<%end%>

app/views/posts/edit.html.erb
<h1> Edit Picture </h1>


<%= render 'form', post: @posts %>

<%= link_to 'Cancel', posts_path %>

app/views/posts/index.html.erb
<div class="container">

<% if signed_in? %>
<% @posts.each do |x| %>
  <div class="white">
    <%= image_tag x.image.url(:medium)%>
    <br>
    <br>
    <p><%= x.description %></p>
    <%= link_to 'Edit', post_path(@posts), method: :put %> |
    <%= link_to 'Delete', post_path(@posts), method: :delete %>
    <br>
    <br>
    <br>
<% end %>
</div>



<%end%>

app/views/posts/new.html.erb
<h2>New Post</h2>
<p>Add your new posts here </p>

<%= form_for @post, html: { multipart: true } do |f| %>
    <%= f.label :image %>
    <%= f.file_field :image%>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.submit %>

<%end%>

app/views/posts/show.html.erb
<h1>Your Upload</h1>
<br>
<p><%= @post.description %></p>
<div class="white">
<%= image_tag(@post.image.url(:medium)) %>
</div>